version: "3"
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kayord
      POSTGRES_USER: kayord
      POSTGRES_PASSWORD: bbHRro5Ju2L9cw
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: PurhsNC7&iTeuc
    ports:
      - "6379:6379"

volumes:
  pgdata:
